last_update = 1687904402361
api_url = "https://api.playit.cloud/agent"
ping_target_addresses = ["23.133.216.1:5530", "ping.ply.gg"]
control_address = "control.playit.gg"
refresh_from_api = true
api_refresh_rate = 5000
ping_interval = 5000
secret_key = "27e6e69d87a8649f83481b27a4f7642121d818a92d147d66dc8c7ba1ffa2a471"

[[mappings]]
name = "FakeInstagram"
proto = "tcp"
tunnel_ip = "147.185.221.181"
tunnel_from_port = 43295
local_ip = "192.168.1.9"
local_port = 3000

[[mappings]]
name = "VikiSmash"
proto = "tcp"
tunnel_ip = "147.185.221.223"
tunnel_from_port = 23390
local_ip = "192.168.1.8"
local_port = 25565
